- name: Configure raid0
  ansible.builtin.import_role:
    name: raid0
  vars:
    raid0_mount_path: /scratch/shared
  when: (ansible_local.nvme.nvme.count | int) > 0

- name: "Create /var/spool/slurmctld directory"
  file:
    path: /var/spool/slurmctld
    state: directory

- name: Start nfs server
  ansible.builtin.import_role:
    name: nfs_server
