- name: Add /home entry to /etc/auto.master
  tags: nfs_client
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    line: /home /etc/auto.home

- name: Copy /etc/auto.home
  tags: nfs_client
  ansible.builtin.template:
    src: auto.home
    dest: /etc/auto.home

- name: Restart autofs
  tags: nfs_client
  ansible.builtin.systemd_service:
    name: autofs
    state: restarted
    enabled: true