- name: Check if /home is mounted
  debug: msg="/home is mounted"
  with_items: "{{ ansible_mounts }}"
  register: home_mount_exists
  when:
    - use_vast_nfs | default(false) | bool
    - item.mount == "/home"
  delegate_to: slurm-login-node-0
  run_once: true

- name: Mount slurm_nfs_home_disk to /mnt/home
  ansible.posix.mount:
    src: "100.64.0.2:/volumes/{{ slurm_nfs_home_disk_id }}"
    path: /mnt/home
    opts: proto=tcp,nconnect=16,spread_reads,spread_writes,remoteports=100.64.0.2-100.64.0.17
    fstype: nfs
    state: mounted
  when: 
    - home_mount_exists is skipped
    - use_vast_nfs | default(false) | bool
  delegate_to: slurm-login-node-0
  run_once: true

- name: Copy /home to /mnt/home
  command: "rsync -a /home/ /mnt/home"
  when: 
    - home_mount_exists is skipped
    - use_vast_nfs | default(false) | bool
  delegate_to: slurm-login-node-0
  run_once: true

- name: Unmount slurm_nfs_home_disk from /mnt/home
  ansible.posix.mount:
    path: /mnt/home
    state: unmounted
  when: use_vast_nfs | default(false) | bool
  delegate_to: slurm-login-node-0
  run_once: true

- name: Mount vastnfs slurm_nfs_home_disk
  ansible.posix.mount:
    src: "100.64.0.2:/volumes/{{ slurm_nfs_home_disk_id }}"
    path: /home
    opts: proto=tcp,nconnect=16,spread_reads,spread_writes,remoteports=100.64.0.2-100.64.0.17
    state: mounted
    fstype: nfs
  when: use_vast_nfs | default(false) | bool