- name: "Add group {{ user_name }}"
  ansible.builtin.group:
    name: "{{ user_name }}"
    gid: "{{ user_gid }}"
    state: present

- name: "Add user {{ user_name }}"
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    uid: "{{ user_uid }}"
    home: "/home/{{ user_name }}"
    shell: "/bin/bash"
    create_home: false
    state: present

- name: "Create home directory for {{ user_name }} on login node"
  ansible.builtin.file:
    path: "/home/{{ user_name }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  delegate_to: >-
    {{ 'slurm-login-node-0' if use_vast_nfs | bool else groups['slurm_nfs_nodes'][0] }}
  run_once: true

- name: "Add authorized key for {{ user_name }}"
  ansible.builtin.authorized_key:
    user: "{{ user_name }}"
    key: "{{ user_ssh_pubkey }}"
  delegate_to: >-
    {{ 'slurm-login-node-0' if use_vast_nfs | bool else groups['slurm_nfs_nodes'][0] }}
  run_once: true