- name: Update mdadm.conf
  ansible.builtin.lineinfile:
    path: /etc/mdadm/mdadm.conf
    state: present
    regexp: '^HOSTNAME'
    line: 'HOSTNAME <ignore>'
  notify: Update initramfs

- name: Copy raid0-enhanced.sh
  ansible.builtin.copy:
    src: raid0-enhanced.sh
    dest: /usr/sbin/raid0.sh
    owner: root
    group: root
    mode: '0644'

- name: Copy raid0.service
  ansible.builtin.template:
    src: raid0.service
    dest: /etc/systemd/system/raid0.service
    owner: root
    group: root
    mode: '0644'

- name: Copy raid0.mount
  ansible.builtin.template:
    src: raid0.mount
    dest: "/etc/systemd/system/{{ raid0_mount_name }}"
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart raid0 service
  ansible.builtin.systemd_service:
    name: raid0.service
    state: restarted
    enabled: true

# - name: Create filesystem if not already present
#   community.general.filesystem:
#     fstype: xfs
#     dev: /dev/md/ephemeral

- name: Restart raid0 mount
  ansible.builtin.systemd_service:
    name: "{{ raid0_mount_name }}"
    state: restarted
    enabled: true
