- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: "Add users"
    ansible.builtin.include_role:
      name: user
    vars:
      user_name: "{{ item.name }}"
      user_uid: "{{ item.uid }}"
      user_ssh_pubkey: "{{ item.ssh_pubkey }}"
    loop: "{{ slurm_users | from_json}}"
    when: slurm_users is defined