- name: Configure autofs
  ansible.builtin.import_role:
    name: autofs
  when:
    - not use_vast_nfs | default(false) | bool
    
- name: Mount /var/spool/slurmctld
  ansible.posix.mount:
    src: >-
      {{
        "slurm-nfs-node-0:/var/spool/slurmctld"
        if not (use_vast_nfs | default(false) | bool)
        else "100.64.0.2:/volumes/" ~ slurmctld_disk_id
      }}
    path: /var/spool/slurmctld
    opts: >-
      {{
        "rw,sync,soft"
        if not (use_vast_nfs | default(false) | bool)
        else "proto=tcp,nconnect=16,spread_reads,spread_writes,remoteports=100.64.0.2-100.64.0.17"
      }}
    state: mounted
    fstype: nfs

- name: Install override.conf
  ansible.builtin.template:
    src: override.conf
    dest: /etc/systemd/system/slurmctld.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Install slurm conf
  ansible.builtin.import_role:
    name: slurm_conf

- name: Restart slurmctld
  ansible.builtin.systemd_service:
    name: slurmctld
    state: restarted
    enabled: true
    daemon_reload: true
