- name: Mount /var/spool/slurmctld
  ansible.posix.mount:
    src: "{{ vast_nfs_server_host }}:/volumes/{{ slurmctld_disk_id }}"
    path: /var/spool/slurmctld
    opts: "vers=3,nconnect=16,spread_reads,spread_writes,remoteports={{ vast_nfs_remoteports }},_netdev,nofail,x-systemd.automount,x-systemd.idle-timeout=30"
    state: mounted
    fstype: nfs

- name: Install override.conf
  ansible.builtin.template:
    src: override.conf
    dest: /etc/systemd/system/slurmctld.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Install slurm conf
  ansible.builtin.import_role:
    name: slurm_conf

- name: Restart slurmctld
  ansible.builtin.systemd_service:
    name: slurmctld
    state: restarted
    enabled: true
    daemon_reload: true
